#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export DOTFILES="$HOME/ghq/github.com/ekosz/dotfiles"
export WORKSPACE="$HOME/workspace"

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# nvim
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_PREVIEW_DIR_CMD="lcd --all --color=always"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# NPM
export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

# git
export GIT_REVIEW_BASE=master # See gitconfig

# volta
export VOLTA_HOME="$HOME/.volta"

# Cargo
source "$HOME/.cargo/env"

# PATH
export PATH="$NPM_BIN:$PATH"                                        # NPM
export PATH="$VOLTA_HOME/bin:$PATH"                                        # NPM
export PATH="$HOME/.cargo/bin:$PATH"                                        # NPM
